// AUTO-GENERATED by tools/build-seed.mjs from recipes.json.
// Each recipe is a Cooklang .cook document (the single source of truth).
// Do not edit by hand - regenerate instead, or edit recipes in the app.

export const DEFAULT_RECIPES = [
  {
    "id": "sausages-potato-veg-sauerkraut",
    "title": "Sausages, Potato, Veg & Sauerkraut",
    "source": "---\ntitle: \"Sausages, Potato, Veg & Sauerkraut\"\n---\n\nGather your ingredients: @nürnberger würstchen{1%pack}, @potatoes{}(chopped into chips), @mixed vegetables{}(defrosted), @sauerkraut{}.\n\nFry sausages\n\nPut potato chips in the oven\n\nDefrost vegetables\n\nCook sauerkraut\n"
  },
  {
    "id": "curry-peanut-noodles",
    "title": "Curry Peanut Noodles",
    "source": "---\ntitle: Curry Peanut Noodles\n---\n\nGather your ingredients: @fettuccine{250%g}, @oil{2%tbsp}, @sugar{1%tsp}, @salted peanuts{40%g}, @chilli{1}(cut in fine strips), @garlic + ginger in oil{30%g}(2 cloves garlic, bit of ginger), @onion{1}(finely chopped), @curry powder{1%tsp}, @vegetable stock{1%tsp}, @peanut butter{2%tbsp}, @red pepper{1}(cut in fine strips), @lime{1}(quartered), @spinach{50%g}, @coconut milk{250%ml}.\n\nCook fettuccine in salted water (and remember to keep 100ml of the cooking water try without)\n\nHeat 1 Tbsp oil, sugar, peanuts and ½ of the chilli and stir until the sugar is melted. Put in a bowl to the side\n\nIn the same pan, heat 1 Tbsp oil. Add garlic + ginger oil, onion and rest of chilli and fry for 1 min\n\nAdd curry powder, stock and peanut butter and fry for 1 min\n\nAdd red pepper, juice from 1 lime quarter, coconut milk and saved cooking water. Mix until sauce is a bit thicker\n\nAdd fettuccine and spinach, mix, season and serve with peanuts and lime quarters\n"
  },
  {
    "id": "quiche",
    "title": "Quiche",
    "source": "---\ntitle: Quiche\n---\n\nGather your ingredients: @short/quiche pastry{200%g}, @butter{2%tbsp}, @Speckwürfel{100%g}(low fat), @onion{2}(chopped), @leek{2}, @flour{4%tbsp}, @milk{500%ml}, @egg{4}, @grated tasty cheese{1%cup}.\n\nPreheat oven to 200°C, line pie dish with pastry and blind bake for 12 minutes\n\nMelt butter in a saucepan. Add bacon, onion and leek. Cook until onion is clear. Stir in flour and cook until frothy. Gradually add milk, stirring constantly until mixture boils and thickens\n\nRemove pan from heat. Lightly beat eggs with a fork. Add eggs and cheese to saucepan. Stir to combine. Season with salt and pepper to taste\n\nPour filling into pastry base. Return to oven and bake for a further 30 minutes or until filling is golden and set\n"
  },
  {
    "id": "schnitzel",
    "title": "Schnitzel",
    "source": "---\ntitle: Schnitzel\n---\n\nGather your ingredients: @schnitzel{}, @green pepper (jar){}, @Schalotten{2}, @KOCHsahne{200%ml}, @vegetable stock{200%ml}, @butter{2%tbsp}, @mushrooms{}, @frozen mixed vegetables{}, @oven potatoes / chips{}, @salt and pepper{}.\n\nFollow cook it recipe\n"
  },
  {
    "id": "spinach-pasta-bake",
    "title": "Spinach Pasta bake",
    "source": "---\ntitle: Spinach Pasta bake\n---\n\nGather your ingredients: @pasta{500%g}, @cherry tomatoes{400%g}(halved), @spinach{400%g}, @mini mozzarella{2%pack}, @KOCHsahne{400%ml}, @water{500%ml}, @vegetable stock{4%tsp}.\n\nLay it all out in a tray and 45 minutes at 180 degrees in oven\n\nmix halfway through\n"
  },
  {
    "id": "leek-potato-soup",
    "title": "Leek + Potato Soup",
    "source": "---\ntitle: Leek + Potato Soup\n---\n\nGather your ingredients: @leek{2}, @potato{4}, @onion{2}, @garlic{2}, @vegetable stock{3%tsp}, @cream{100%ml}, @garlic bread{1}.\n\nfollow cookit recipe\n"
  },
  {
    "id": "spaghetti-aglio-e-olio",
    "title": "Spaghetti Aglio e Olio",
    "source": "---\ntitle: Spaghetti Aglio e Olio\n---\n\nGather your ingredients: @broccoli{}(mouthsize cut; head / 2 servings), @olive oil{100%ml}, @garlic{2}(chopped), @spaghetti{250%g}, @parmesan cheese{100%g}(grated).\n\nCut the broccoli including the stem into small pieces\n\nBlanch the broccoli in boiling salted water for 5 minutes in the colander\n\nHeat the oil and fry the garlic. Immediately add the broccoli with some of its cooking water\n\nCook the spaghetti in the broccoli water\n\nLet the broccoli cook over low heat until the spaghetti is ready, then add spaghetti to the pan\n\nSeason with salt and pepper and mix parmesan in\n"
  },
  {
    "id": "diavolo-flammkuchen-salad",
    "title": "Diavolo Flammkuchen + Salad",
    "source": "---\ntitle: Diavolo Flammkuchen + Salad\n---\n\nGather your ingredients: @red onions{2}, @Flammkuchenteig (ready-made){2}, @rote Spitzpaprika{2}, @chorizo{100%g}, @grated Gouda{100%g}, @pasta sauce{400%g}, @chilli{}, @Romana salad{300%g}, @Mittelscharfer Senf{2%tsp}, @Weißweinessig / Condimento Italiano Blanco{2%tsp}, @olive oil{2%tbsp}, @sugar{1%pinch}.\n\nCut the onions in half and then in fine stripes\n\nCut the Spitzpaprika in fine rings\n\nCut the chorizo in strips or 0.5cm cubes\n\nHeat the oven to 200°C\n\nSpread the Teig on 2 oven trays\n\nSpread the pasta sauce on the Teig\n\nGrind some chili and spread the cheese on top\n\nSpread the onion, paprika and chorizo\n\nBake for 18-22 min\n\nMeanwhile, wash the salad and prepare the salad dressing\n\nMix 2 tsp Senf, 2 Tbsp Olive oil, 2 tsp Essig, salt, pepper and a pinch of sugar\n\nCut the Romana into 2cm strips and mix into the dressing\n"
  },
  {
    "id": "kottbullar-mash-potatoe",
    "title": "Köttbullar & Mash potatoe",
    "source": "---\ntitle: \"Köttbullar & Mash potatoe\"\n---\n\nGather your ingredients: @potatoes{1%kg}, @butter{100%g}, @salt{1%tsp}, @frozen Köttbullar{500%g}, @Köttbullar sauce fix packet{}(or Rahmsoße + 1 tsp soy sauce + ½ tsp mustard), @KOCHsahne{200%ml}, @Preiselbeere jam{}, @peas{}.\n\nmake it like Ikea\n"
  },
  {
    "id": "thai-basil-noodles",
    "title": "Thai Basil Noodles",
    "source": "---\ntitle: Thai Basil Noodles\n---\n\nGather your ingredients: @green beans{200%g}(halved), @udon noodles{250%g}, @onion{1}(finely chopped), @garlic{1}(finely chopped), @ginger{15%g}(finely chopped), @basil{10%g}, @oil{2%tbsp}, @sweet chilli sauce{50%g}, @soy sauce{50%ml}, @maple syrup{10%ml}, @salted peanuts{20%g}, @chilli{1}.\n\nBoil a pot of salted water\n\nCut beans in half\n\nSteam beans for 8 minutes and add noodles to water and cook for necessary time\n\nFinely chop onion and garlic\n\nFinely chop ginger and basil\n\nMix sweet chilli sauce, soy sauce, syrup, ginger and 2 Tbsp water to make a sauce\n\nHeat oil in a pan. Fry onion and garlic until clear\n\nAdd noodles and beans and fry for 1 minute\n\nAdd sauce and ¼ of the basil, simmer for 30 seconds, then serve with the rest of the basil, peanuts and chilli to taste\n"
  },
  {
    "id": "leek-pea-and-pepper-risotto",
    "title": "Leek, Pea and Pepper Risotto",
    "source": "---\ntitle: Leek, Pea and Pepper Risotto\n---\n\nGather your ingredients: @vegetable stock{1¼%l}, @olive oil{1%tbsp}, @red pepper{2}(sliced), @leek{1}(chopped), @risotto rice{300%g}, @frozen peas{150%g}, @parmesan cheese{50%g}(grated), @chives{1%bunch}(chopped).\n\nHeat oil and fry the red pepper and leek until softened\n\nAdd rice and cook for 1 minute\n\nAdd the stock, one ladle at a time, stirring and waiting for the rice to absorb the liquid before adding more. Continue until the rice is just cooked and the risotto has a creamy consistency\n\nStir in peas to heat through\n\nSeason, then stir through most of the parmesan and chives, saving a little of each to scatter over before serving\n"
  },
  {
    "id": "maultaschen",
    "title": "Maultaschen",
    "source": "---\ntitle: Maultaschen\n---\n\nGather your ingredients: @maultaschen{2%pack}(1 cm stripes), @onion{1}(chopped into rings), @olive oil{1%tbsp}.\n\nCook Maultaschen in olive oil until crispy\n\nAdd onion rings at the end and cook until clear\n"
  },
  {
    "id": "one-pot-pasta",
    "title": "One-Pot Pasta",
    "source": "---\ntitle: \"One-Pot Pasta\"\n---\n\nGather your ingredients: @cream{100%ml}, @courgettes{1}(chopped), @chopped tomatoes{1%can}, @onion{1}(chopped), @garlic{1}(chopped), @oregano{2%tsp}, @water{380%ml}(1 can), @salt{1%tsp}, @chilli{1}, @wholewheat pasta{250%g}.\n\nPut everything in a big pot, cover and bring to a boil. Move the pasta around so it doesn’t stick together\n\nAfter 10 minutes reduce heat and cook without a lid for 5 minutes. If the pasta is too hard, add a bit more water\n\nSeason with salt and pepper\n"
  },
  {
    "id": "gnocchipfanne-mit-pesto",
    "title": "Gnocchipfanne mit Pesto",
    "source": "---\ntitle: Gnocchipfanne mit Pesto\n---\n\nGather your ingredients: @walnuts{20%g}, @garlic{}, @olive oil{2%tbsp}, @water{2%tbsp}, @parmesan cheese{20%g}(grated), @basil{20%g}, @spinach{200%g}, @cream cheese{70%g}, @onion{1}(chopped), @gnocchi{600%g}.\n\nMake Pesto\n\nBlend walnuts, garlic, olive oil, water, parmesan, basil and spinach. Then add cream cheese, salt and pepper\n\nMake Gnocchi\n\nFry the onions until clear.\n\nAdd gnocchi and fry until golden brown.\n\nAdd spinach and half of the pesto.\n\nServe gnocchi topped with pesto, a blob of cream cheese, basil and fresh pepper\n"
  },
  {
    "id": "fish-sticks-potato-veg",
    "title": "Fish Sticks, Potato & Veg",
    "source": "---\ntitle: \"Fish Sticks, Potato & Veg\"\n---\n\nGather your ingredients: @fish fingers{}, @potato slices or frozen chips{}, @vegetables{}.\n\nPut fish fingers with potatoes in the oven until ready\n\nDefrost vegetables\n"
  },
  {
    "id": "spicy-coconut-soup",
    "title": "Spicy Coconut Soup",
    "source": "---\ntitle: Spicy Coconut Soup\n---\n\nGather your ingredients: @olive oil{2%tbsp}, @red pepper{1}(2cm diced), @spring onions{1%bunch}(sliced), @garlic{1}(chopped), @curry powder{1%tsp}, @chopped tomatoes{1%can}, @kidney beans{1%can}(rinsed), @coconut milk{1%can}, @corn tortillas{}(cut to triangles), @lime juice{}, @grated coconut{}.\n\nHeat 1 Tbsp of Olive Oil, fry red pepper, white spring onions, and garlic for 3-5 minutes\n\nAdd curry powder, tomato, kidney beans, and coconut milk. Season with salt and pepper. Simmer for 10-12 minutes\n\nSpread tortillas on a tray and drizzle with 1 Tbsp olive oil. Put into the grill oven until lightly browned\n\nAdd lime juice to soup\n\nServe and garnish with green spring onions and grated coconut\n"
  },
  {
    "id": "one-pot-pasta-with-spinach-and-pine-nuts",
    "title": "One-Pot Pasta with Spinach and Pine Nuts",
    "source": "---\ntitle: \"One-Pot Pasta with Spinach and Pine Nuts\"\n---\n\nGather your ingredients: @pine nuts{10%g}, @olive oil{1%tbsp}, @onion{1}(chopped), @garlic{1}(chopped), @pasta{250%g}, @hot water{500%ml}, @vegetable stock{1%tsp}, @salt{½%tsp}, @chilli{1}(deseeded, chopped finely), @cherry tomatoes{125%g}(quartered), @cream cheese{100%g}, @calabrese pesto{50%g}, @spinach{100%g}, @parmesan cheese{40%g}(grated).\n\nRoast pine nuts in an oil-free pot stirring until light brown, set aside\n\nIn the same pot, heat oil and fry onion and garlic until glassy\n\nAdd pasta, hot water, vegetable stock, and salt. Boil, cover and cook for 9 minutes. Remember to stir\n\nWhile pasta is cooking, cut the chilli and tomatoes\n\nAdd cream cheese, pesto, and chilli to the pasta and mix to become a sauce\n\nAdd spinach and cherry tomatoes to the pasta\n\nServe pasta with roasted pine nuts and grated parmesan\n"
  },
  {
    "id": "eggs-benedict",
    "title": "Eggs Benedict",
    "source": "---\ntitle: Eggs Benedict\n---\n\nGather your ingredients: @english muffins{4}, @bacon{1%pack}, @hash browns{8}, @eggs{4}, @hollandaise sauce{}.\n"
  },
  {
    "id": "tortellini-pikante",
    "title": "Tortellini Pikante",
    "source": "---\ntitle: Tortellini Pikante\n---\n\nGather your ingredients: @tortellini with ricotta{800%g}, @olive oil{2%tbsp}, @onion{2}(chopped), @garlic{4}(chopped), @chilli powder{2%tsp}, @chopped tomatoes{2%can}, @green olives{150%g}(halved), @basil{6%tbsp}(chopped), @mozzarella balls{2}.\n\nCook tortellini al-dente\n\nHeat olive oil and fry onion\n\nAdd garlic and chilli powder and fry\n\nAdd tomato, season and cook for 15 min\n\nAdd olives and basil to the sauce\n\nPut everything mixed together in an ovenproof dish\n\nCover with mozzarella and bake in the oven for 15-20 min at 200°C\n"
  },
  {
    "id": "moroccan-pot",
    "title": "Moroccan Pot",
    "source": "---\ntitle: Moroccan Pot\n---\n\nGather your ingredients: @olive oil{1%tbsp}, @potato{1}(1 cm cubes), @onion{1}(chopped), @garlic{1}(chopped), @water{250%ml}, @chopped tomatoes{1%can}, @cumin{0.5%tsp}, @chilli{0.5%tsp}, @vegetable stock{1%tsp}, @chickpeas{1%can}(drained), @spinach{50%g}, @oregano{1%tsp}, @parsley{1%tsp}(chopped), @lemon{1}(zested and quartered), @creme fraiche{200%g}, @flatbreads{1-2}(quartered), @butter{}, @garlic{2-4}(chopped).\n\nHeat oil. Fry potato, onion and garlic for 2-3 minutes. Add water.\n\nAdd chopped tomatoes, cumin, chilli and vegetable stock. Cover and cook for 12 minutes.\n\nAdd chickpeas, spinach and oregano and cook for another ~3 minutes until the potato cubes are soft.\n\nSeason with salt and pepper.\n\nParsley dip: Grate 2 tsp lemon zest, then quarter the lemon.\n\nMix the creme fraiche, parsley, lemon zest, a little lemon juice, salt and pepper.\n\nFlat bread: Add a bit of butter, garlic and salt to a frying pan and fry a flatbread quarter. Repeat for the remaining quarters.\n\nServe with lemon quarters.\n"
  },
  {
    "id": "mexican-beef-nachos",
    "title": "Mexican Beef Nachos",
    "source": "---\ntitle: Mexican Beef Nachos\n---\n\nGather your ingredients: @beef{500%g}, @taco seasoning{}, @onion{1}(finely chopped), @spring onions{1%bunch}(sliced), @grated cheese{70%g}, @tomato{1}(diced), @sour cream{1}, @nachos{}, @avocado{}, @tomato{}.\n\nFry beef and onion\n\nMix everything on a tray and cover with cheese, grill until cheese is melted\n"
  },
  {
    "id": "cheesy-tuna-melts",
    "title": "Cheesy Tuna Melts",
    "source": "---\ntitle: Cheesy Tuna Melts\n---\n\nGather your ingredients: @tuna{2%can}, @spring onions{2%bunch}(chopped), @remoulade{8%tbsp}, @toastbrötchen{8}, @cheddar cheese{}(grated), @paprika{2%pinch}.\n\nPreheat the grill to its highest setting\n\nMix everything except paprika. Season with salt and pepper\n\nSpread tuna mix on bread and sprinkle cheese over\n\nGrill until cheese bubbles\n\nSprinkle paprika on top\n"
  },
  {
    "id": "blue-cheese-fettuccine",
    "title": "Blue Cheese Fettuccine",
    "source": "---\ntitle: Blue Cheese Fettuccine\n---\n\nGather your ingredients: @fettuccine{250%g}, @Kaisergemüse{750%g}, @olive oil{2%tbsp}, @onion{1}(chopped), @garlic{1}(chopped), @cream{200%ml}, @vegetable stock{200%ml}, @gorgonzola{150%g}(cubed), @nutmeg{1%pinch}, @parsley{30%g}(chopped).\n\nFry chicken strips, season with salt and pepper then set aside\n\nCook fettuccine and steam broccoli over the top\n\nHeat olive oil and fry onion until glassy\n\nAdd garlic and fry for 1 minute\n\nAdd cream and stock and simmer for a short time\n\nReduce heat and add gorgonzola, stirring until it has melted. Season with salt, pepper, and nutmeg\n\nMix the sauce with the fettuccine, broccoli, and chicken and garnish with parsley\n"
  },
  {
    "id": "coconut-lentil-curry",
    "title": "Coconut Lentil Curry",
    "source": "---\ntitle: Coconut Lentil Curry\n---\n\nGather your ingredients: @onion{1}(chopped), @garlic{2}(chopped), @ginger{2%cm}(chopped), @tomato paste{2%tbsp}, @curry powder{2%tbsp}, @chilli{½%tsp}, @vegetable stock{1%l}, @coconut milk{1%can}, @chopped tomatoes{1%can}, @red lentils{1%cup}, @rice{1%cup}, @spinach{2%handful}.\n\nFry onion, garlic, and ginger for a few minutes\n\nAdd tomato paste, curry powder, and chilli flakes. Cook for 1 minute\n\nAdd stock, coconut milk, tomato can, lentils, rice, and spinach\n\nCover, bring to the boil, simmer on low for 20-30 mins until lentils are cooked\n\nSeason with salt and pepper\n"
  },
  {
    "id": "spatzle-in-raclette-kase-soe",
    "title": "Spätzle in Raclette-Käse-Soße",
    "source": "---\ntitle: \"Spätzle in Raclette-Käse-Soße\"\n---\n\nGather your ingredients: @apple{1}, @onions{2}, @butter{12%g}, @honey{1%tsp}, @balsamico essig{1%tsp}, @petersilie{10%g}, @oil{10%g}, @porree{1}(big), @eierspätzle frisch{500%g}, @Nutmeg{1}, @tumeric{1}, @KOCHsahne{200%g}, @raclette käse{125%g}.\n"
  },
  {
    "id": "vegetable-soup",
    "title": "Vegetable Soup",
    "source": "---\ntitle: Vegetable Soup\n---\n\nGather your ingredients: @soup vege mix{}, @garlic bread{}.\n"
  },
  {
    "id": "butter-chicken",
    "title": "Butter Chicken",
    "source": "---\ntitle: Butter Chicken\n---\n\nGather your ingredients: @yoghurt (3.5% fat){2%tbsp}, @vegetable oil{3%tbsp}, @lemon juice{3%tbsp}, @ground turmeric{½%tsp}, @chilli powder{½%tsp}, @rose paprika powder{1%tsp}, @garam masala{1%tsp}, @chicken breast fillet{3}(approx. 200 g each, diced (2 cm)), @onions{2}(peeled, halved, approx. 80 g each), @garlic cloves{3}(peeled), @ginger{1}(walnut-sized, peeled), @vegetable oil{50%ml}, @butter{50%g}, @ground turmeric{½%tsp}, @rose paprika powder{½%tsp}, @chilli powder{½%tsp}, @ground coriander{½%tsp}, @garam masala{1%tsp}, @ground cumin{½%tsp}, @salt{1%tsp}, @ground black pepper{½%tsp}, @sugar{½%tsp}, @tomatoes{500%g}, @cream{200%ml}, @cornstarch{1%tbsp}, @water{1%tbsp}, @cream{}(for garnish), @fresh coriander{}(to garnish), @black pepper{}(coarsely crushed, for garnish).\n\nfollow cookit recipe\n"
  },
  {
    "id": "smashed-potato-yoghurttzatziki-pesto-and-onion-rings",
    "title": "Smashed potato, yoghurt/tzatziki, pesto and onion rings",
    "source": "---\ntitle: Smashed potato, yoghurt/tzatziki, pesto and onion rings\n---\n\nGather your ingredients: @potatoes{5}, @tzatziki{1}, @onion{1}(rings), @green pesto{1}.\n\neverything in the oven\n\nserve with Tzatziki and Pesto\n"
  },
  {
    "id": "courgette-pasta",
    "title": "Courgette Pasta",
    "source": "---\ntitle: Courgette Pasta\n---\n\nGather your ingredients: @olive oil{3%tbsp}, @garlic{1}(crushed), @courgettes{2}(quartered and sliced), @fettuccine{250%g}, @cream{1%cup}, @lemon{1}(grated zest and juice), @parmesan cheese{20%g}(grated), @nutmeg{1%pinch}.\n\nHeat the oil in a pan over medium heat. Add garlic and courgettes and cook gently for 10 minutes, stirring occasionally\n\nMeanwhile cook the pasta in boiling salt water according to the packet instructions\n\nAdd the cream and lemon to the courgette mixture. Add cheese, nutmeg, salt, and pepper. Heat through gently\n\nDrain the pasta, add to the sauce, mix and serve immediately\n\nDecorate with some more cheese and a candle on the table\n"
  },
  {
    "id": "fish-and-chips",
    "title": "Fish and Chips",
    "source": "---\ntitle: Fish and Chips\n---\n\nGather your ingredients: @chips{}, @fish{}.\n\neverything in the oven and bake it\n\nwarm up vegetables\n"
  },
  {
    "id": "mac-and-cheese",
    "title": "Mac and Cheese",
    "source": "---\ntitle: Mac and Cheese\n---\n\nGather your ingredients: @macaroni pasta{250%g}, @butter{40%g}, @flour{40%g}, @curry powder{1%tsp}, @milk{400%ml}, @mustard{1%tbsp}, @chilli sauce{1%tsp}, @nutmeg{½%tsp}, @grated cheese{120%g}, @parmesan cheese{50%g}, @mixed vegetables{}.\n\nCook pasta, then pour into an ovenproof dish\n\nMelt butter, then add flour and curry powder and whisk over low heat until mixture bubbles and separates.\n\nAdd milk gradually, whisking constantly.\n\nAdd mustard, chilli sauce, nutmeg, salt, and pepper and whisk until thickened.\n\nMix in 100g of the grated cheese\n\nSteam vegetables\n\nPour sauce over cooked pasta, sprinkle parmesan/remaining cheese on top and grill until golden\n"
  }
];

export const EXAMPLE_RECIPE = {
  "id": "example-pancakes",
  "title": "Example Pancakes",
  "source": "---\ntitle: Example Pancakes\n---\n\nGather your ingredients: @eggs{2}, @plain flour{125%g}, @milk{250%ml}, @sea salt{1%pinch}, @butter{1%knob}.\n\nCrack the @eggs{2} into a #blender, add the @plain flour{125%g}, @milk{250%ml} and @sea salt{1%pinch}, and blitz until smooth.\n\nPour into a #bowl and leave to stand for ~{15%minutes}.\n\nMelt the @butter{1%knob} in a #frying pan{} and cook each pancake for ~{2%minutes} a side.\n"
};

// Default staples and shopping links (seeded into each user's book).
export const DEFAULT_STAPLES = [
  "milk",
  "milk",
  "oats",
  "toast bread",
  "flour",
  "pizza",
  "yoghurt",
  "fruit",
  "apples",
  "banana",
  "eggs",
  "boring cheese",
  "yummi cheese",
  "butter",
  "Rosenbrötchen"
];

export const DEFAULT_FOOD_LINKS = {
  "allgäuer bergkäse": "https://shop.rewe.de/p/allgaeuer-sonthofner-bergkaese-mild/8245695",
  "bacon": "https://shop.rewe.de/p/ja-delikatess-bacon-100g/961733",
  "band noodles / fettuccine": "https://shop.rewe.de/p/rewe-beste-wahl-bandnudeln-mit-frischei-500g/7193879",
  "basil": "https://shop.rewe.de/p/kraeuter-basilikum-xl-im-topf/8363134",
  "beef": "https://shop.rewe.de/p/ja-rinder-hackfleisch-500g/7978794",
  "broccoli": "https://shop.rewe.de/p/ja-broccoli-roeschen-tiefgefroren-1kg/7073900",
  "butter": "https://shop.rewe.de/p/ja-markenbutter-mild-gesaeuert-250g/5883121",
  "calabrese pesto": "https://shop.rewe.de/p/ja-pesto-alla-calabrese-190g/8268091",
  "carrot": "https://shop.rewe.de/p/karotten-2kg/8339524",
  "cauliflower": "https://shop.rewe.de/p/ja-blumenkohl-tiefgefroren-1kg/7067903",
  "cheddar cheese": "https://shop.rewe.de/p/ja-cheddar-in-scheiben-175g/8926272",
  "cherry tomatoes": "https://shop.rewe.de/p/cherry-romatomaten-250g/1033906",
  "chicken": "https://shop.rewe.de/p/ja-haehnchen-brustfilet-600g/8468236",
  "chickpeas": "https://shop.rewe.de/p/ja-kichererbsen-265g/7814109",
  "chilli flakes": "https://shop.rewe.de/p/rewe-beste-wahl-chiliflocken-geschrotet-26g/8333001",
  "chilli powder": "https://shop.rewe.de/p/rewe-beste-wahl-chili-mix-gemahlen-39g/8600803",
  "chilli": "https://shop.rewe.de/p/chili-mix-tricolor-80g/8229761",
  "chips": "https://shop.rewe.de/p/ja-curly-fries-pikant-gewuerzt-600g/8074238",
  "chives": "https://shop.rewe.de/p/rewe-bio-schnittlauch-50g/184645",
  "chopped tomatoes": "https://shop.rewe.de/p/ja-tomaten-fein-gehackt-in-tomatensaft-400g/973336",
  "coconut milk": "https://shop.rewe.de/p/ja-kokosmilch-400g/7738173",
  "corn tortillas": "https://shop.rewe.de/p/ja-weizen-tortillas-372g/8842634",
  "courgettes": "https://shop.rewe.de/p/zucchini-gruen-ca-220g/482161",
  "cream cheese": "https://shop.rewe.de/p/ja-frischkaese-natur-doppelrahmstufe-300g/2421597",
  "cream": "https://shop.rewe.de/p/ja-schlagsahne-200g/64840",
  "creme fraiche": "https://shop.rewe.de/p/ja-cr-me-fra-che-classic-30-fett-200g/8444108",
  "curry powder": "https://shop.rewe.de/p/ja-curry-gemahlen-45g/2788275",
  "eggs": "https://shop.rewe.de/p/ja-frische-eier-aus-bodenhaltung-10-stueck/7937888",
  "english muffins": "https://shop.rewe.de/p/ja-mehrkorn-toastbroetchen-335g/8696982",
  "fettuccine": "https://shop.rewe.de/p/rewe-beste-wahl-bandnudeln-mit-frischei-500g/7193879",
  "fish fingers": "https://shop.rewe.de/p/ja-fischstaebchen-450g-15-stueck/6540147",
  "fish": "https://shop.rewe.de/p/ja-knusperfilet-mit-kaese-kraeuter-fuellung-400g/8878429",
  "flatbreads": "https://shop.rewe.de/p/harry-fladenbrot-500g/3958043",
  "flour": "https://shop.rewe.de/p/ja-weizenmehl-type-405-1kg/6729550",
  "frozen mixed veggies": "https://shop.rewe.de/p/ja-bunte-gemuesemischung-1kg/9074580",
  "frozen peas": "https://shop.rewe.de/p/ja-junge-erbsen-1kg/7083761",
  "garlic + ginger in oil": "https://shop.rewe.de/p/bio-ingwer-ca-100g/1218820",
  "garlic": "https://shop.rewe.de/p/knoblauch-200g-im-netz/1041139",
  "ginger": "https://shop.rewe.de/p/bio-ingwer-ca-100g/1218820",
  "gnocchi": "https://shop.rewe.de/p/ja-gnocchi-di-patate-500g/592755",
  "gorgonzola": "https://shop.rewe.de/p/marca-italia-gorgonzola-200g/8335191",
  "grated cheese": "https://shop.rewe.de/p/ja-geriebener-emmentaler-45-fett-250g/8428056",
  "grated coconut": "https://shop.rewe.de/p/ja-kokosraspeln-200g/1008594",
  "green olives": "https://shop.rewe.de/p/ja-gruene-oliven-ohne-stein-170g/8075601",
  "hash browns": "https://shop.rewe.de/p/ja-roesti-ecken-750g/7948844",
  "hollandaise sauce": "https://shop.rewe.de/p/ja-sauce-hollandaise-340g/7627371",
  "hot water": "#",
  "kidney beans": "https://shop.rewe.de/p/ja-kidney-bohnen-rot-255g/914670",
  "leek": "https://shop.rewe.de/p/porree-1-stueck/8311846",
  "lemon": "https://shop.rewe.de/p/zitrone-1-stueck/1970267",
  "lime juice": "https://shop.rewe.de/p/leverno-limetten-fix-100ml/1055439",
  "macaroni pasta": "https://shop.rewe.de/p/ja-hoernchen-frischei-nudeln-500g/7196141",
  "maultaschen": "https://shop.rewe.de/p/ja-schwaebische-maultaschen-360g/8669105",
  "milk": "https://shop.rewe.de/p/ja-frische-vollmilch-3-5-1l/2865690",
  "mince": "https://shop.rewe.de/c/fleisch-fisch/?search=hackfleisch%20ja&sorting=PRICE_ASC",
  "mini mozzarella": "https://shop.rewe.de/p/ja-mini-mozzarella-125g/8066826",
  "mozzarella": "https://shop.rewe.de/p/ja-mozzarella-125g/8434947",
  "mushrooms": "https://shop.rewe.de/p/champignons-braun/479225",
  "mustard": "https://shop.rewe.de/p/bautz-ner-senf-mittelscharf-200ml/6685234",
  "nachos": "https://shop.rewe.de/p/ja-tortilla-chips-nacho-cheese-300g/2502892",
  "nürnberger würstchen": "https://shop.rewe.de/p/ja-original-nuernberger-rostbratwuerstchen-300g/8309744",
  "olive oil": "https://shop.rewe.de/p/ja-natives-olivenoel-extra-750ml/420386",
  "onion": "https://shop.rewe.de/p/zwiebel-rot-500g-im-netz/1041143",
  "oregano": "https://shop.rewe.de/p/rewe-beste-wahl-oregano-gerebelt-11g/8013483",
  "parmesan cheese": "https://shop.rewe.de/p/marca-italia-grana-padano-gerieben-150g/8716397",
  "parmesan": "https://shop.rewe.de/p/marca-italia-grana-padano-gerieben-150g/8716397",
  "parsley": "https://shop.rewe.de/p/rewe-bio-petersilie-50g/184650",
  "pasta": "https://shop.rewe.de/p/ja-fusilli-500g/8069766",
  "pine nuts": "https://shop.rewe.de/p/ja-pinienkerne-50g/2325000",
  "potato": "https://shop.rewe.de/p/kartoffeln-festkochend-ca-100g/466182",
  "red pepper": "https://shop.rewe.de/p/paprika-rot-500g/1902921",
  "red lentils": "https://shop.rewe.de/p/rewe-bio-rote-linsen-500g/7547310",
  "reis": "https://shop.rewe.de/c/reis/?search=Reis%20ja&sorting=PRICE_ASC",
  "risotto rice": "https://shop.rewe.de/p/ja-milchreis-500g/2107010",
  "salt": "https://shop.rewe.de/p/ja-jodsalz-500g/2037971",
  "salted peanuts": "https://shop.rewe.de/p/ja-erdnuesse-geroestet-gesalzen-200g/2310347",
  "sauerkraut": "https://shop.rewe.de/p/spreewaldhof-sauerkraut-650g/659258",
  "schallots": "https://shop.rewe.de/p/schalotten-250g-im-netz/1041140",
  "spaghetti": "https://shop.rewe.de/p/ja-spaghetti-500g/687999",
  "spinach": "https://shop.rewe.de/p/rewe-beste-wahl-junger-spinat-450g/157118",
  "spring onions": "https://shop.rewe.de/p/lauchzwiebeln-im-bund/482404",
  "spätzle": "https://shop.rewe.de/p/ja-frische-eierspaetzle-500g/2411378",
  "taco seasoning": "https://shop.rewe.de/p/fuego-taco-seasoning-mix-gewuerzzubereitung-30g/7849008",
  "tomato paste": "https://shop.rewe.de/p/ja-tomatenmark-3-fach-konzentriert-200g/5944481",
  "tortellini with ricotta": "https://shop.rewe.de/p/ja-tortelloni-ricotta-spinat-250g/2272449",
  "tzatziki": "https://shop.rewe.de/p/ja-zaziki-200g/8618614",
  "vegetable stock": "https://shop.rewe.de/p/ja-klare-gemuesebruehe-140g/7033086",
  "water": "#",
  "wholewheat pasta": "https://shop.rewe.de/p/rewe-bio-vollkorn-spaghetti-500g/209834",
  "garlic bread": "https://shop.rewe.de/p/ja-knoblauchbutter-baguette-175g/2360956",
  "toast or english muffins": "https://shop.rewe.de/p/ja-mehrkorn-toastbroetchen-335g/8696982",
  "tuna": "https://shop.rewe.de/p/ja-thunfischfilets-in-eigenem-saft-geschnitten-150g/2063277",
  "pizza": "https://shop.rewe.de/productList?attribute=discounted&search=pizza",
  "apples": "https://shop.rewe.de/c/obst-gemuese/?search=apfel&sorting=PRICE_ASC",
  "banana": "https://shop.rewe.de/p/banane-ca-200g/455217",
  "breadroll": "https://shop.rewe.de/c/broetchen/?search=br%C3%B6tchen&sorting=PRICE_ASC",
  "specials": "https://shop.rewe.de/angebote?attribute=discounted&objectsPerPage=250&sorting=PRICE_ASC",
  "toasties": "https://www.rewe.de/shop/p/ja-mehrkorn-toastbroetchen-335g/8696982",
  "soup vege mix": "https://www.rewe.de/shop/p/suppengruen-500g/482293"
};

// The account whose book is seeded with the full default recipe collection.
// Every other user starts from the single example recipe.
export const SEED_OWNER_EMAIL = "iwanicki.rm@gmail.com";
